name: George L.W. Zard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61409
title: 'Thoughts, some times criminal, always exquisite'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2b5c0'
    - '#09090a'
    - '#41586b'
    - '#7a93a4'
    - '#efeeed'
  brandStrength: 0.25
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
